name: Sync main into sync-me branch

on: 
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  merge-main-into-sync-me-branch:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Merge main into sync-me branch
      run: |
          git fetch --unshallow
          git checkout sync-me
          git pull
          git merge --no-ff main -m "Auto-merge main branch"
          git push
